# Automatically build multi-architectural tagged container images and push them to DockerHub
# https://github.com/FNNDSC/cookiecutter-chrisapp/wiki/Automatic-Builds

name: ci

on:
  push:
    branches: [ main ]
    tags: [ '**' ]

jobs:
  publish:
    if: github.event_name == 'push' || github.event_name == 'release'
    runs-on: ubuntu-20.04

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - name: Get git tag
        id: git_info
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "::set-output name=tag::${GITHUB_REF##*/}"
      - name: Decide image tag name
        id: determine
        env:
          git_tag: ${{ steps.git_info.outputs.tag }}
        run: |
          repo="${GITHUB_REPOSITORY,,}"  # to lower case
          # if build triggered by tag, use tag name
          tag="${git_tag:-latest}"

          # if tag is a version number prefixed by 'v', remove the 'v'
          if [[ "$tag" =~ ^v[0-9].* ]]; then
            tag="${tag:1}"
          fi

          dock_image=$repo:$tag
          echo $dock_image
          echo "::set-output name=dock_image::$dock_image"
          echo "::set-output name=repo::$repo"

      - uses: actions/checkout@v2

      # QEMU is for emulating non-x86_64 platforms
      - uses: docker/setup-qemu-action@v1
      # buildx is the next-generation docker image builder
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      # save some time during rebuilds
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        id: dockerhub_login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          file: ./Dockerfile
          tags: |
            ${{ steps.determine.outputs.dock_image }}
            localhost:5000/${{ steps.determine.outputs.dock_image }}
            ghcr.io/${{ steps.determine.outputs.dock_image }}
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Run examples
        run: |
          dock_image=${{ steps.determine.outputs.dock_image }}
          output_dir=$(mktemp -d)
          docker run --rm -u "$(id -u):$(id -g)" \
            -v "$PWD/examples/incoming:/incoming:ro" \
            -v "$output_dir:/outgoing:rw" \
            localhost:5000/$dock_image niis2mncs /incoming /outgoing
          
          for expected_file in $(find examples/outgoing -type f); do
            fname="${expected_file##*/}"
            out_path="$output_dir/$fname"
            printf "Checking output %s exists..." "$out_path"
            if [ -f "$out_path" ]; then
              echo "ok"
            else
              echo "not found"
              exit 1
            fi
          done

      - name: Get plugin meta
        id: pluginmeta
        run: |
          repo=${{ steps.determine.outputs.repo }}
          dock_image=${{ steps.determine.outputs.dock_image }}
          docker run --rm localhost:5000/$dock_image chris_plugin_info > /tmp/description.json
          jq < /tmp/description.json  # pretty print in log
          echo "::set-output name=title::$(jq -r '.title' < /tmp/description.json)"

      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@v2
        continue-on-error: true  # it is not crucial that this works
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          short-description: ${{ steps.pluginmeta.outputs.title }}
          readme-filepath: ./README.md
          repository: ${{ steps.determine.outputs.repo }}

      - name: Upload to ChRIS Store
        if: "!endsWith(steps.determine.outputs.dock_image, ':latest')"
        uses: FNNDSC/chrisstore-action@master
        with:
          descriptor_file: /tmp/description.json
          auth: ${{ secrets.CHRIS_STORE_USER }}
